services:
  postgres:
    image: postgres:17
    container_name: collaboration-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: collaboration_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Target@Google23
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: